jdbc:
  driverClassName: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://1.15.243.183:3306/studentsystem?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
  username: root
  password: zcjdsql
 #激活其他配置文件；需要指定其他的配装文件名称
spring:
  profiles:
    active: abc,bilibili

  #mvc:
    #view: /WEB-INF
      #prefix: .html

  #springboot自带的kikari数据库连接池
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://1.15.243.183:3306/studentsystem?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: zcjdsql
  #配置redis数据库
  redis:
    host: localhost
    port: 6379

#配置SpringMVC视图前后缀
server:
  port: 8080
#tomcat端口修改

#日志记录级别
logging:
  cn.zcj: debug
  org.springframework: info

#配置Mybatis
mybatis:
  #实体类别名包
  type-aliases-package: cn.zcj.domain
  #映射文件路径
  #mapper-locations: classpath:mappers/*.xml
  #日志配置
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
